[[constraint]]
  name = "github.com/fatih/color"
  version = "1.5.0"

[[constraint]]
  name = "github.com/mattn/go-isatty"
  version = "0.0.2"

[[constraint]]
  name = "github.com/pkg/profile"
  version = "1.2.1"

[[constraint]]
  branch = "master"
  name = "github.com/spf13/pflag"

[[constraint]]
  branch = "master"
  name = "github.com/zchee/go-xdgbasedir"
